# Generated by Django 5.2.10 on 2026-04-26 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalLevel',
            fields=[
                ('id_emotional_level', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Emotional Level',
                'verbose_name_plural': 'Emotional Levels',
                'db_table': 'mh_emotional_level',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'mh_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id_response_option', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Response Option',
                'verbose_name_plural': 'Response Options',
                'db_table': 'mh_response_option',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id_intervention', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('action', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('emotional_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='mental_health.emotionallevel')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'db_table': 'mh_intervention',
            },
        ),
    ]
