# Generated by Django 6.0.4 on 2026-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0002_evaluation_evaluationanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
