# Generated by Django 6.0.4 on 2026-05-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0005_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseoption',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
