# Generated by Django 6.0.4 on 2026-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0006_alter_responseoption_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('ansiedad', 'Ansiedad'), ('depresion', 'Depresión'), ('estres', 'Estrés'), ('bienestar', 'Bienestar')], default='bienestar', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
