# Generated by Django 6.0.4 on 2026-05-13 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0007_question_category_question_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionProgress',
            fields=[
                ('id_progress', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('reflection', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='mental_health.evaluation')),
            ],
            options={
                'db_table': 'mh_intervention_progress',
            },
        ),
    ]
